//! Autogenerated Code.
//! Manual edits may be overwritten on rebuild.

const tknzr = @import("tokenizer.zig");
const Token = tknzr.Token;
const Tokenizer = tknzr.Tokenizer;
const std = @import("std");
const Alloc = std.mem.Allocator;

const ___ = @This();
fn __aToString(comptime a: anytype) []const u8 {
    return @tagName(a); // todo support strings too
}
fn GetResType(comptime aname: []const u8) type {
    if (!@hasDecl(___, aname)) @compileError("unknown type " ++ aname);
    return @field(___, aname);
}
pub fn parse(alloc: *Alloc, code: []const u8, comptime a: anytype) !GetResType(__aToString(a)) {
    const aname = comptime __aToString(a);
    const ResType = GetResType(aname);
    const resfn = @field(___, "parse" ++ aname);

    var parser = Parser.init(alloc, code);
    defer parser.deinit();

    // TODO: @resultLocation().* = …
    const outmain = try resfn(&parser);
    if ((try parser.nextToken())) |tok| {
        std.debug.panic("Remaining token: {}\n", .{tok});
    }
    return outmain;
}
pub const Parser = struct {
    alloc: *Alloc,
    tokenizer: Tokenizer,
    tokens: std.ArrayList(Token),
    tkpos: usize = 0,
    errors: ?[]const u8 = null,
    fn init(alloc: *Alloc, code: []const u8) Parser {
        return .{
            .alloc = alloc,
            .tokenizer = Tokenizer.init(code),
            .tokens = std.ArrayList(Token).init(alloc),
        };
    }
    fn deinit(parser: *Parser) void {
        parser.tokens.deinit();
    }
    fn err(parser: *Parser, message: []const u8) ParseError {
        parser.errors = message;
        return ParseError.ParseError;
    }
    fn nextToken(parser: *Parser) ParseError!?Token {
        if (parser.tkpos >= parser.tokens.items.len) {
            const nextToken_ = parser.tokenizer.next() catch return parser.err("bad token");
            try parser.tokens.append(nextToken_ orelse return null);
        }
        defer parser.tkpos += 1;
        return parser.tokens.items[parser.tkpos];
    }
    fn startBit(parser: Parser) usize {
        return parser.tkpos;
    }
    fn cancelBit(parser: *Parser, prevPos: usize) void {
        parser.tkpos = prevPos;
    }
};

pub const ParseError = error{
    OutOfMemory,
    ParseError,
};

fn _parseToken(parser: *Parser, tokenKind: Token.Type, expectedText: ?[]const u8) ParseError!Token {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    const tok = (try parser.nextToken()) orelse return parser.err("err");
    if (tok.kind != tokenKind) return parser.err("err");
    if (expectedText) |txt| if (!std.mem.eql(u8, tok.text, txt)) return parser.err("err");

    return tok;
}

pub const Math = _8;
const _8 = union(enum) {
    plus_op: []_8,
    times_op: []_8,
    parens: _6,
    number: _7,
};
const _2 = []const u8;
const _5 = []const u8;
const _6 = *Parens;
const _7 = *Number;
fn _9(parser: *Parser) ParseError!_8 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    var resAL = std.ArrayList(_8).init(parser.alloc);
    _ = _10(parser) catch |e| switch (e) {
        error.OutOfMemory => return e,
        error.ParseError => {},
    }; // optional first joiner
    while (true) {
        try resAL.append(_11(parser) catch |e| switch (e) {
            error.OutOfMemory => return e,
            error.ParseError => return parser.err("last or disallowed"),
        });
        _ = _10(parser) catch |e| switch (e) {
            error.OutOfMemory => return e,
            error.ParseError => break,
        };
    }
    if (resAL.items.len == 0) return parser.err("no items");
    if (resAL.items.len == 1) return resAL.items[0];

    return _8{ .plus_op = resAL.toOwnedSlice() };
}
fn _11(parser: *Parser) ParseError!_8 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);
    var resAL = std.ArrayList(_8).init(parser.alloc);
    _ = _12(parser) catch |e| switch (e) {
        error.OutOfMemory => return e,
        error.ParseError => {},
    }; // optional first joiner
    while (true) {
        try resAL.append(_13(parser) catch |e| switch (e) {
            error.OutOfMemory => return e,
            error.ParseError => return parser.err("last or disallowed"),
        });
        _ = _12(parser) catch |e| switch (e) {
            error.OutOfMemory => return e,
            error.ParseError => break,
        };
    }
    if (resAL.items.len == 0) return parser.err("no items");
    if (resAL.items.len == 1) return resAL.items[0];

    return _8{ .times_op = resAL.toOwnedSlice() };
}
fn _13(parser: *Parser) ParseError!_8 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);
    blk: {
        return _8{
            .parens = _14(parser) catch |e| switch (e) {
                error.OutOfMemory => return e,
                error.ParseError => break :blk,
            },
        };
    }
    blk: {
        return _8{
            .number = _15(parser) catch |e| switch (e) {
                error.OutOfMemory => return e,
                error.ParseError => break :blk,
            },
        };
    }
    return parser.err("union field not matched f");
}
fn _10(parser: *Parser) ParseError!_2 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    return (try _parseToken(parser, .punctuation, "+")).text;
}
fn _12(parser: *Parser) ParseError!_5 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    return (try _parseToken(parser, .punctuation, "*")).text;
}
fn _14(parser: *Parser) ParseError!_6 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    const _16 = try parseParens(parser);
    const _17 = try parser.alloc.create(@TypeOf(_16));
    _17.* = _16;
    return _17;
}
fn _15(parser: *Parser) ParseError!_7 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    const _18 = try parseNumber(parser);
    const _19 = try parser.alloc.create(@TypeOf(_18));
    _19.* = _18;
    return _19;
}
pub const parseMath = _9;
pub const Parens = _23;
const _23 = struct {
    math: _21,
};
const _20 = []const u8;
const _21 = *Math;
const _22 = []const u8;
fn _24(parser: *Parser) ParseError!_23 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    _ = try _25(parser);
    const _27 = try _26(parser);
    _ = try _28(parser);
    return _23{
        .math = _27,
    };
}
fn _25(parser: *Parser) ParseError!_20 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    return (try _parseToken(parser, .punctuation, "(")).text;
}
fn _26(parser: *Parser) ParseError!_21 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    const _29 = try parseMath(parser);
    const _30 = try parser.alloc.create(@TypeOf(_29));
    _30.* = _29;
    return _30;
}
fn _28(parser: *Parser) ParseError!_22 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    return (try _parseToken(parser, .punctuation, ")")).text;
}
pub const parseParens = _24;
pub const Number = _31;
const _31 = []const u8;
fn _32(parser: *Parser) ParseError!_31 {
    const sb = parser.startBit();
    errdefer parser.cancelBit(sb);

    return (try _parseToken(parser, .identifier, "a")).text;
}
pub const parseNumber = _32;
